name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 0 * * *'   # tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -o /dev/null -s -w "HTTP %{http_code}" \
            "$SUPABASE_URL/rest/v1/prospections?select=id&limit=1" \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
